### ISSUE TITLE
TDP is not re applied after wake up from sleep

### ISSUE THREAD

**Issue by adolfotregosa** [aarron-lee/SimpleDeckyTDP#11]
I have to change tdp slider so it gets reapplied or maybe changing something is enough but you have to do something.

(not related but the z from MHz gets moved bellow MH in minimum and maximum is already bellow, it's ugly :D )
(There is a situation e.g. you change maximum gpu freq but minimum cannot go higher, you have to lower min before you can make it go higher)

**Comment by aarron-lee** [comment]
Hrm, it should be applying on suspend-resume. I'll investigate now, in the meanwhile you can turn on polling as a temp workaround

**Comment by aarron-lee** [comment]
pushed a quick fix for the MHz getting moved below. Still investigating the suspend issue, you are using a ROG ally?

**Comment by aarron-lee** [comment]
> I have to change tdp slider so it gets reapplied or maybe changing something is enough but you have to do something.

I can't replicate the bug on the Legion Go. I think this might be related to [this](https://github.com/mengmeet/PowerControl/pull/18),

This is what it says after running it through Google translate:

> According to the plug-in log, the plug-in did call the SetTDP logic and called ryzenadj when waking up.
> After reading the documentation of ryzenadj, I suspect that the underlying ryzenadj does not take effect due to some system-level power consumption scheduling when waking up.

For now I've added the same fix as described by this end user, added an additional [10s timeout for setting with ryzenadj](https://github.com/aarron-lee/SimpleDeckyTDP/blob/2c197ede8d4032deb8b8d68d8e2aa827ad8b61eb/src/steamListeners.tsx#L41)

**Comment by aarron-lee** [comment]
The best long-term solution would probably be to setup a custom tdp method of some sort that avoids ryzenadj altogether: https://github.com/aarron-lee/SimpleDeckyTDP#custom-tdp-method

And eventually incorporate it into the plugin itself

**Comment by adolfotregosa** [comment]
yes rog ally. 

This is the bug, watch with sound 
https://youtu.be/pHq5OqXozDQ

**Comment by aarron-lee** [comment]
> This is the bug, watch with sound https://youtu.be/pHq5OqXozDQ

i shipped a change to the gpu slider behavior, which might resolve the issue. I haven't been able to reproduce the issue with this newer implementation, let me know if you still encounter the bug.

**Comment by adolfotregosa** [comment]
> > This is the bug, watch with sound https://youtu.be/pHq5OqXozDQ
> 
> i shipped a change to the gpu slider behavior, which might resolve the issue. I haven't been able to reproduce the issue with this newer implementation, let me know if you still encounter the bug.

This implementation is brilliant ! Thank you. Closing
