### ISSUE TITLE
UI is gone when going to desktop mode and back or switching user account

### ISSUE THREAD

**Issue by SerjTargarien** [aarron-lee/SimpleDeckyTDP#13]
Plugin version 0.0.5.5. 

The plugin works as advertised on first boot of the os, but if I temporarily leave gaming mode to go to the OS desktop or change users the plugin UI is empty and no settings can be changed. The problem fixes itself if I restart the whole system.

I'm on Chimera OS on an Ayn Loki.

**Comment by aarron-lee** [comment]
Hrm, I can't replicate your issue with going to desktop mode and back.

When you say `switch users`, I'm assuming you mean another steam account?

**Comment by SerjTargarien** [comment]
I mean using the steam bug picture setting to change accounts, but I believe under the hood it probably restart gamescope-session, so it may be the same issue. It's the only plugin with the issue for me and it didn't happen before 0.0.5.5.

**Comment by aarron-lee** [comment]
> It's the only plugin with the issue for me and it didn't happen before 0.0.5.5.

Oh interesting, could you try installing the releases from here and figure which version introduced the bug? https://github.com/aarron-lee/SimpleDeckyTDP/tags

**Comment by SerjTargarien** [comment]
Will do as soon as possible 👌

**Comment by aarron-lee** [comment]
> Will do as soon as possible 👌

One other thing you could try doing is deleting the `$HOME/homebrew/settings/SimpleDeckyTDP/settings.json` file.

Note that this will delete all TDP profiles, so you could optionally move it somewhere else to keep it as a backup.

It could be that resetting the settings.json file will fix things up.

**Comment by SerjTargarien** [comment]
The bug is absent in 0.0.4.4, but appears in 0.0.5.4 and 0.0.5.5. 

Tested in both Decky Stable and Prerelease. Steam Deck Stable and Beta.

**Comment by aarron-lee** [comment]
Nice, glad that resetting the settings file fixed it. I'll add it to the README as a troubleshooting step.
