### ISSUE TITLE
Polling should be able to be force disabled

### ISSUE THREAD

**Issue by th3raid0r** [aarron-lee/SimpleDeckyTDP#14]
Ever since the recent BIOS and running in STAMP mode I've not experienced my device switching TDPs unintentionally. 

Thus, the latest fix actually breaks a "feature" of the program that I've come to depend on - the ability to quick toggle my TDP with Legion+Y. 

If, instead, it only performed a "set" operation when the "custom" profile is currently active - THAT makes sense and I'd appreciate that. But as it stands it will change it back to custom - thereby requiring TDP be set from the QAM/SimpleDeckyTDP menu. 

If this feature _must_ persist, could you at least allow me to disable it? Force enabling this seemed a fair bit heavy-handed to me for an issue that I had never once experienced. 

Also - if we are unable to toggle polling now, could you at least remove the UI toggle so that such fact is better communicated?

**Comment by aarron-lee** [comment]
fixed in https://github.com/aarron-lee/SimpleDeckyTDP/releases/tag/v0.0.5.8

Just as a heads up though, in STAMP mode + custom TDP mode, there have been reports of the TDP value getting changed by the bios.
