### ISSUE TITLE
Feature Request - Option to patch steam TDP slider instead of adding a new one

### ISSUE THREAD

**Issue by SerjTargarien** [aarron-lee/SimpleDeckyTDP#19]
The PowerControl plugin by mengmeet patches and uses the main TDP slider in the performance tab, and in the case of PowerTools for the official Steam Deck, they don't need it because the Deck already uses the Steam provided TDP slider.

I just think it looks cleaner to use the TDP control settings we already have avaliable in the UI rather than having one you have to ignore and one you have to adjust. I understand it may be too hacky or there may be multiple other reasons not to do it that way, but would love to have that option otherwise.

**Comment by aarron-lee** [comment]
going to investigate this for now, but no guarantees on if this will be implemented.

**Comment by aarron-lee** [comment]
Added Steam Patch as an advanced option 

![simple_steam_patch](https://github.com/aarron-lee/SimpleDeckyTDP/assets/9145965/2ae558a0-77ff-4240-8789-985563df617c)
