### ISSUE TITLE
SMT and CPU Boost Options

### ISSUE THREAD

**Issue by cerdafyed** [aarron-lee/SimpleDeckyTDP#23]
CPU Boost and SMT option toggles were removed, is this permanent? Turning off SMT increased performance for certain emulators, and the official PowerTools app doesn't play well with non-steam deck devices like this plug-in does

**Comment by aarron-lee** [comment]
> CPU Boost and SMT option toggles were removed, is this permanent? Turning off SMT increased performance for certain emulators, and the official PowerTools app doesn't play well with non-steam deck devices like this plug-in does

Regarding SMT, currently there's a bug where disabling SMT prevents the plugin from being able to manage power governors and energy profiles.

most SMT-related bugs with emulators were fixed on Linux kernel version v6.1, so I deemed it safe to remove SMT control.

CPU boost will depend on your `scaling-driver`, which you'll see listed at the bottom of the plugin.

If you are willing to permanently change your scaling driver from `amd-pstate-epp` to `amd-pstate`, the cpu boost toggle will show up again.

**Comment by aarron-lee** [comment]
Note that if I see an opportunity to re-add the functionality back on future updates, I will try to do so.

For CPU boost, it'll probably require this: https://www.phoronix.com/news/AMD-Core-Perf-Boost-Linux

**Comment by aarron-lee** [comment]
SMT toggle has been fixed + re-added as of v0.2.3

**Comment by aarron-lee** [comment]
re-adding CPU boost will be re-visited once the changes are on kernel 6.9: https://www.phoronix.com/news/AMD-Core-Perf-Boost-Linux

Note that the CPU Boost toggle is still available in the plugin for scaling drivers `amd-pstate` and `acpi-cpufreq`
