### ISSUE TITLE
Feature request: Custom TDP based on FPS limits

### ISSUE THREAD

**Issue by 4uva4ek** [aarron-lee/SimpleDeckyTDP#26]
Hi. I saw good things in HandheldCompanion for windows  - its custom TDP based on FPS. Does it really to do in SimpleDeckyTPD?

**Comment by aarron-lee** [comment]
I could investigate it, but it wouldn't happen anytime soon

**Comment by aarron-lee** [comment]
not planned. i'll reopen the issue if I end up changing plans in the future
