### ISSUE TITLE
add custom fan curve for rog ally

### ISSUE THREAD

**Issue by semakusut** [aarron-lee/SimpleDeckyTDP#27]
hello, i use simpledeckytdp on my ally, it's work great, can you help adding simple fancurve profile that was already set in asusctl, because when i boot from shutdown before the fancurve not work, need to back to desktopmode and enable it from asusctl, or enable it manually from terminal using this command sudo asusctl fan-curve -g, thx i hope you can add this

**Comment by aarron-lee** [comment]
I wasn't planning on adding any fan curve controls to SimpleDeckyTDP. Have you already tried [PowerControl](https://github.com/mengmeet/PowerControl) for TDP + fan control? might be better than SimpleDeckyTDP for your use case.

**Comment by aarron-lee** [comment]
fan control support is not planned to be included in SimpleDeckyTDP
