### ISSUE TITLE
The TDP slider no longer visible in Steam UI after May 7th update.

### ISSUE THREAD

**Issue by habisoft** [aarron-lee/SimpleDeckyTDP#32]
After installing the May 7th Steam client update, the TDP slider is no longer visible in the Steam UI performance settings.

Note that using the controls provided by the Decky TDP plugin UI is still working properly, so this might be a workaround.

**Comment by aarron-lee** [comment]
Yep, it looks like Steam might've disabled the TDP slider on non-deck devices in their latest client update. There's not much I can do about it, so I might have to remove the `Steam Hardware Fix` functionality from SDTDP.

**Comment by aarron-lee** [comment]
`Steam Hardware Fix` option has been officially removed in [v0.3.5](https://github.com/aarron-lee/SimpleDeckyTDP/releases/tag/v0.3.5) due to Steam Client changes. 

The code itself is still in the codebase, so it can be reactivated if the TDP slider ever returns.
