### ISSUE TITLE
Different device name for ROG Ally on latest chimeraos kernel

### ISSUE THREAD

**Issue by gifter77** [aarron-lee/SimpleDeckyTDP#38]
On latest chimeraos testing build (Linux chimeraos 6.9.9-chos1-chimeraos-1 kernel), the device name for the ROG Ally seems to have changed:
```
[gamer@chimeraos ~]$ cat /sys/devices/virtual/dmi/id/product_name
ROG Ally RC71L_RC71L
```
So the device name checks in the plugin fail.

**Comment by aarron-lee** [comment]
thanks for the report, I'll update the device detection

**Comment by aarron-lee** [comment]
just pushed a release with a fix for the ROG Ally dmi check: https://github.com/aarron-lee/SimpleDeckyTDP/releases/tag/v0.4.0

let me know if it doesn't work for you

**Comment by gifter77** [comment]
All good in the new version thanks!
