### ISSUE TITLE
Steam Deck OLED TDP

### ISSUE THREAD

**Issue by Wayne992** [aarron-lee/SimpleDeckyTDP#45]
Hey,
I installed Everthing.
The TDP Slider also working but only Till 15 Watt.
I cant get tge TDP above 15 Watts.
I tried with Power Tools and IT worked but Not with ryzenadj Auto TDP...
In Desctop Mode i can ready my Watt and IT tells me ITS 21000. So ist should Work...
Did i Miss Something?

**Comment by aarron-lee** [comment]
:thinking: This plugin is for non-Deck handhelds, it won't work for TDP controls on an actual Deck.

**Comment by Wayne992** [comment]
Ahh.. 
Ist there another way to Pump Up TDP without powertools on Steam Deck ? 
Power Tools works , but i have to restart Always the settings :/

**Comment by aarron-lee** [comment]
Hrm, to be honest I have no idea. I never investigated increasing the TDP on the Deck.

Wish I could help you more, but I don't own any Deck hardware.

**Comment by aarron-lee** [comment]
Closing for now since there's no plans to support TDP controls on an actual Steam Deck at the moment
