### ISSUE TITLE
Complete removal? It's killing my 6900HX mini pc

### ISSUE THREAD

**Issue by ExpatUK** [aarron-lee/SimpleDeckyTDP#46]
I think this plugin got auto installed with either the decky 3.0.1 or last EmuDeck update, and it's absolutely ruined the machine this weekend as it defaulted down to a TDP of 12 (with a max of 40) on a system with a max TDP of 65 W. 

Uninstalling it through the UI, removing settings.json and rebooting has had no effect.

Could someone tell me precisely what this pokes and where that persists between reboots please?

**Comment by ExpatUK** [comment]
For anyone else with this same issue, delete the plugin and make your own ryzenadj adjustments yourself - for me, this was:
`ryzenadj --stapm-limit=65000 --fast-limit=65000 --slow-limit=65000 --tctl-temp=93 --max-performance`

I might have a grep through the python to see if anything else gets played with.

Leaving this issue open as it completely demolished my HTPC when it was installed with some update or other.

**Comment by aarron-lee** [comment]
? this was automatically installed on a device? SDTDP needs to be manually installed.

Which distro?

**Comment by aarron-lee** [comment]
you can also remove it manually by doing `sudo rm -rf ~/homebrew/plugins/SimpleDeckyTDP`

worst case scenario, you can go into the plugin and disable TDP controls by flipping the toggle `Enable TDP Controls` off

**Comment by aarron-lee** [comment]
Also, none of the changes SDTDP makes are permanent.

You can uninstall the plugin, and reboot the device for to get default values back.

**Comment by ExpatUK** [comment]
Yeah, I’m as perplexed as you. 

Nobara 40 HTPC Edition, had a kernel update last night and also EmuDeck self-updated - I think the latter is the culprit as it also installs Decky with some pre-configuration. 

I’m not sure how the changes persisted through a reboot but they did - several. Running the above ryzenadj command got me back to normal, after removal. 

How do you pull the max TDP number btw? Mine’s a 6900HX SER6 from Beelink configured to 65W in the bios.

**Comment by aarron-lee** [comment]
> Nobara 40 HTPC Edition

Ah, I think I had vaguely heard about SDTDP getting pre-installed on Nobara, I thought it was going to be for handhelds-only or something.

As for the max TDP number, it's actually not pulled from anywhere, it's user configurable. I just set a hard cap of 40W, since this is typically installed on handheld PCs that don't go above 30-40W TDP.

If you want to go beyond the 40W limit, you can do so by manually editing the `settings.json` in `~/homebrew/settings/SimpleDeckyTDP/settings.json`

That being said, since you're on an HTPC, I doubt you need any of this.

**Comment by aarron-lee** [comment]
And for future reference, there currently is no way that I know of to pull a `max supported TDP` value from the system.

There's some current talks in LKML about potentially supporting this sort of functionality for AMD handhelds, but nothing set in stone yet.

**Comment by aarron-lee** [comment]
closing for now, since this seems to be something that Nobara has installed automatically
